[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--tb=short",
    "--strict-markers",
    "--disable-warnings",
    "--html=reports/report.html",
    "--self-contained-html"
]
markers = [
    "smoke: marks tests as smoke tests (quick validation)",
    "integration: marks tests as integration tests",
    "ui: marks tests as UI tests requiring browser",
    "api: marks tests as API tests",
    "slow: marks tests as slow running",
    "regression: marks tests as regression tests"
]
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]
# Minimum version requirements
minversion = "6.0"

[tool.coverage.run]
source = ["src", "app"]
omit = [
    "*/tests/*",
    "*/venv/*",
    "*/__pycache__/*",
    "*/migrations/*"
]

[tool.coverage.report]
show_missing = true
skip_covered = false
precision = 2
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:"
]

[tool.coverage.html]
directory = "reports/coverage"