services:
  - type: web
    name: python-trivia
    env: python
    repo: https://github.com/bholsinger09/PythonTrivia.git
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: python-trivia-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.6

databases:
  - name: python-trivia-db
    databaseName: python_trivia
    user: python_trivia_user
    plan: free